# Here you can define credentials for different data sets and environment.

# Here you can define training and inference configuration for training and inference pipeline.

# Example:

[DATA]
DATASETS = ['arrhythmia','annthyroid','cardio','shuttle','satimage2','satellite','thyroid']
# DATASETS = ['arrhythmia']

SEEDS = [1,20,42,50,99,101,135,145,165,200]

[SEMI_SUPERVISED_SETTING]
ANOMALIES_FRACTION = [0.1]
NORMALIES_RATIO = [0]
COMTAINATION_RATIO = [0]

[MULTI_CLASS_AD_SETTING]
KNOWN_ANOMALY_CLASS = {"multi_annthyroid"=2, "multi_covertype"=4, "multi_cardio"=2, "multi_shuttle"=3, "multi_har"=2} 
# ALL_CLASSES = {'multi_annthyroid'=[3, 1, 2], 'multi_covertype'=[2, 4, 6], 'multi_cardio'=[1, 2, 3], 'multi_shuttle'=[1, 2, 3, 4, 5, 6, 7], 'multi_har'=[1, 2, 3, 4, 5, 6]}
NORMAL_CLASSES = {'multi_annthyroid'=[3], 'multi_covertype'=[2], 'multi_cardio'=[1], 'multi_shuttle'=[1], 'multi_har'=[1, 4, 5, 6]}

